default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
default_language_version:
  python: python3.13
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        types_or: [python]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: ["--locked", "--all-packages"]
        stages: [post-checkout, post-merge, post-rewrite]
        always_run: true
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt"]
