[project]
name = "leetcode-ds-algo"
dependencies = [
    "numpy>=2.0.0",
    "matplotlib>=3.9.1",
    "scipy>=1.14.0",
]
requires-python = ">=3.11"
readme = "README.md"

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
notebook = [
    "ipykernel>=6.29.5",
]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_defs = true
