[project]
name = "leetcode-ds-algo"
dependencies = [
    "numpy>=2.0.0",
    "matplotlib>=3.9.1",
    "scipy>=1.14.0",
    "networkx>=3.4.2",
]
requires-python = ">=3.11"
readme = "README.md"

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
notebook = [
    "ipykernel>=6.29.5",
]
lint-fmt = [
    "isort>=5.13.2",
    "mypy>=1.13.0",
]

[tool.mypy]
python_version = "3.11"

[[tool.mypy.overrides]]
module = "networkx"
ignore_missing_imports = true
