name: CI Python Setup

on:
  workflow_dispatch: 
  push:
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: leetcode_ds_algo

      - name: Install dependencies
        run: |
          pdm install --prod
