name: CI Python Setup

on:
  push:
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'
      - '.github/workflows/ci_python_setup.yml'
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'
      - '.github/workflows/ci_python_setup.yml'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew install gfortran

      - name: Install dependencies
        run: |
          pdm install --prod
